/*
  ==============================================================================

    ModulationControl — the eight modulation control signals of Fig. 8.

    Section 3.2: "Suitably filtered or frequency-weighted signals from the main
    signal path are rectified, and in some cases smoothed, and are fed in
    opposition to the control signals generated by the control circuits of the
    various stages."

    Each MC signal is a *single scalar* control voltage in the analog, not a
    per-frequency quantity, so each is computed here as one weighted level per STFT
    frame. The weighting is applied in the frequency domain and combined in power,
    normalised by the weight's own norm,

        MC = sqrt (sum over bins of (w_k * mag_k)^2) / sqrt (sum over bins of w_k^2)

    which is the weighted RMS of the per-bin magnitudes. The normalisation is
    load-bearing: without it the sum grows with the number of bins under the
    weighting, so the same programme would read a different MC at every transform
    size — a sample-rate dependence the analog has no counterpart of — and on
    broadband material the raw sum sits tens of times above any single bin's
    magnitude, which is the wrong scale to oppose a per-bin control signal with.
    Normalised, an MC value is on the same per-bin magnitude scale as the spectrum
    it came from: a flat spectrum of magnitude m inside the weighted region reads
    close to m whatever the rate. The 1967 paper notes that a combination of peak
    and average detection is a sufficient proxy for RMS; this is the
    frequency-domain form of that.

    Take-off points follow section 3.2: MC1 to MC7 come from the second-stage adder
    output, MC8 from just after the spectral skewing networks, because for MC8 "the
    influences of the HLS and MLS stages are undesirable".

    Two features of the analog are not reproducible in this form, and are noted
    rather than faked:

      - The all-pass phase networks on MC1 and MC4 exist to optimise the phase of
        the MC signal against the stage control signal, reducing control ripple.
        These are scalar levels per frame with no phase, so there is nothing for an
        all-pass to act on.
      - MC8's double differentiator uses 15 us time constants, three hundred times
        shorter than the 5.33 ms frame interval at 48 kHz. Its purpose is to detect
        high-frequency transients, so it is realised as the rising part of the
        frame-to-frame change in high-frequency level, followed by the specified
        30 ms peak hold.

  ==============================================================================
*/

#pragma once

#include <array>
#include <vector>

namespace lime
{

/** Weighting corners quoted in section 3.2 and Fig. 8. */
namespace mcWeighting
{
    inline constexpr double hfSlidingHighPassHz = 3000.0;      // MC1, MC2
    inline constexpr double hfFixedLowPassOneHz = 400.0;       // MC3, cascaded
    inline constexpr double hfFixedLowPassTwoHz = 800.0;
    inline constexpr double lfSlidingLowPassHz = 200.0;        // MC4, MC5
    inline constexpr double lfFixedHighPassOneHz = 800.0;      // MC6, MC7, cascaded
    inline constexpr double lfFixedHighPassTwoHz = 1600.0;
    inline constexpr double transientHighPassHz = 5000.0;      // MC8

    inline constexpr double hfSlidingOvershootTauMs = 1.0;     // MC2, two stages
    inline constexpr double lfSlidingOvershootTauMs = 2.0;     // MC5, two stages
    inline constexpr double lfFixedOvershootTauMs = 2.0;       // MC7, two stages
    inline constexpr double transientPeakHoldMs = 30.0;        // MC8
}

//==============================================================================
class ModulationControl
{
public:
    void prepare (int numBins, double sampleRate, int fftSize, double frameSeconds);
    void reset();

    /** Advances one frame, computing the full set of eight signals.

        @param stageFeed  magnitude spectrum at the second-stage adder output,
                          the take-off for MC1 to MC7
        @param skewFeed   magnitude spectrum just after spectral skewing, used
                          only for MC8
    */
    void processFrame (const double* stageFeed, const double* skewFeed);

    /** Advances only the signal the engine's side chains actually consume — MC1
        for the high-frequency half, MC4 for the low — and returns it.

        The full set costs three further weighted passes over the spectrum and
        three smoothers per frame for values nothing in the signal path reads;
        processFrame remains for the tests and for anyone extending the set. The
        skipped signals simply hold their last value. */
    double processFrameEssential (const double* stageFeed, bool highFrequency);

    double hfSliding()          const noexcept { return values[0]; }   // MC1
    double hfSlidingOvershoot() const noexcept { return values[1]; }   // MC2
    double hfFixed()            const noexcept { return values[2]; }   // MC3
    double lfSliding()          const noexcept { return values[3]; }   // MC4
    double lfSlidingOvershoot() const noexcept { return values[4]; }   // MC5
    double lfFixed()            const noexcept { return values[5]; }   // MC6
    double lfFixedOvershoot()   const noexcept { return values[6]; }   // MC7
    double hfTransient()        const noexcept { return values[7]; }   // MC8

    /** 1-based access, matching the paper's numbering. */
    double get (int mcNumber) const noexcept { return values[(size_t) (mcNumber - 1)]; }

    int getNumBins() const noexcept { return numBins; }

private:
    /** Two cascaded one-pole smoothers, as the paper's "two-stage" integrators. */
    struct TwoStageSmoother
    {
        double coeff = 0.0, a = 0.0, b = 0.0;

        void setTau (double tauMs, double frameSeconds);
        void reset() { a = b = 0.0; }
        double process (double input);
    };

    int numBins = 0;

    std::vector<double> weightHfSliding, weightHfFixed;
    std::vector<double> weightLfSliding, weightLfFixed;
    std::vector<double> weightTransient;

    // sqrt (sum of w^2) per table, computed once in prepare, so every MC reads as
    // a weighted RMS on the per-bin magnitude scale whatever the transform size.
    double normHfSliding = 1.0, normHfFixed = 1.0;
    double normLfSliding = 1.0, normLfFixed = 1.0;
    double normTransient = 1.0;

    TwoStageSmoother smootherMc2, smootherMc5, smootherMc7;

    double previousTransientLevel = 0.0;
    double transientHold = 0.0;
    double transientDecay = 0.0;

    std::array<double, 8> values {};
};

} // namespace lime
